//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lend
    {
        public int Id { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DateBorrowed { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public string State { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual User User { get; set; }
    }
}
