//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Contnet { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
