//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibrary.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Lend = new HashSet<Lend>();
            this.History = new HashSet<History>();
        }
    
        public int Id { get; set; }

        [Display(Name = "Imiê")]
        public string FirstName { get; set; }

        [Display(Name = "Nazwisko")]
        public string LastName { get; set; }

        public string Email { get; set; }

        [Display(Name = "Zweryfikowany?")]
        public bool IsUserVerified { get; set; }

        [Display(Name = "Rola")]
        public string Role { get; set; }

        [Display(Name = "Has³o")]
        public string Password { get; set; }

        [Display(Name = "Limit wypo¿yczeñ")]
        public Nullable<int> BorrowLimit { get; set; }

        [Display(Name = "Limit oczekiwania")]
        public Nullable<int> WaitLimit { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lend> Lend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> History { get; set; }
    }
}
